invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, generate_PDF, view_PDF

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download'),
]

meer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from meerapp import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from invoice.views import (
    InvoiceListView,
    createInvoice,
    view_PDF,
    generate_PDF,
    change_status,
)
from meerapp.views import UniformFormView, UniformListView

urlpatterns = [
    # Authentication
    path('', views.index_view, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/create/', views.create_account, name='create_account'),
    path('accounts/', views.account_list, name='account_list'),
    path('accounts/<int:account_id>/', views.account_detail, name='account_detail'),
    #path('income-statement/', views.income_statement, name='income-statement'),
    #path('income_statement/', views.income_statement, name='income_statement'),
    path('balance_sheet/', views.balance_sheet, name='balance_sheet'),
    path('accounts/<int:account_id>/balance-sheet/', views.account_balance_sheet, name='account_balance_sheet'),
    path('invoices/<int:invoice_id>/', views.invoice_details, name='invoice_details'),
    path('invoices/<int:invoice_id>/create-item/', views.create_invoice_item, name='create_invoice_item'),
    path('add_journal_entry/', views.add_journal_entry, name='add_journal_entry'),
    path('accounts/trial_balance/', views.trial_balance, name='trial_balance'),
    path('journal-entries/<int:year>/<int:month>/', views.journal_entries_by_month_year, name='journal_entries_by_month_year'),
    path('add_employee/', views.add_employee, name='add_employee'),  # Add a new employee
    path('edit_employee/<int:employee_id>/', views.edit_employee, name='edit_employee'),  # Edit an employee
    path('delete_employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),  # Delete an employee
    path('employee_list/', views.employee_list, name='employee_list'),  # List all employees
    path('trash/', views.trash, name='trash'),
    path('restore_employee/<int:employee_id>/', views.restore_employee, name='restore_employee'),

    path('head_of_accounts/', views.head_of_accounts, name='head_of_accounts'),
    path('add_head_of_account/', views.add_head_of_account, name='add_head_of_account'),
    path('transactions/', views.transactions, name='transactions'),
    path('add_transaction/', views.add_transaction, name='add_transaction')
    ,
    path('mark-attendance/', views.mark_attendance, name='mark_attendance'),
    path('attendance-list/', views.attendance_list, name='attendance_list'),  # Add this line
    path('attendance-report/', views.attendance_report, name='attendance-report'),
    path('create_salary/', views.create_salary, name='create_salary'),
    path('list_salaries/', views.list_salaries, name='list_salaries'),
    path('calculate_salaries/', views.calculate_salaries, name='calculate_salaries'),
    path('weapons/', views.WeaponListView.as_view(), name='weapon-list'),
    path('weapons/<int:pk>/', views.WeaponDetailView.as_view(), name='weapon-detail'),
    path('weapons/add/', views.WeaponCreateView.as_view(), name='weapon-create'),
    path('location/<int:location_id>/', views.location_detail, name='location_detail'),
    path('location/<int:location_id>/assign_guards/', views.assign_guards, name='assign_guards'),
    path('location/add/', views.add_location, name='add_location'),
    path('locations/', views.location_list, name='location_list'),
    path('get_total_overtime/', views.get_total_overtime, name='get_total_overtime'),
    path('employee_report/<int:employee_id>/', views.employee_report, name='employee_report'),
    path('view_salary_detail/<int:salary_id>/', views.view_salary_detail, name='view_salary_detail'),
    path('uniform-form/', UniformFormView.as_view(), name='uniform_form'),
    path('uniform-list/', UniformListView.as_view(), name='uniform_list'),
    path('invoices/', include('invoice.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/models.py
from django.db import models
import datetime

class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.EmailField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    message = models.TextField(default= "this is a default message.")
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    status = models.BooleanField(default=False)
    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class LineItem(models.Model):
    customer = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    description = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.customer)
   

invoice/forms.py
from django import forms
from django.forms import formset_factory
from .models import Invoice
class InvoiceForm(forms.Form):
    
        # fields = ['customer', 'message']
    customer = forms.CharField(
        label='Cusomter',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Customer/Company Name',
            'rows':1
        })
    )
    customer_email = forms.CharField(
        label='Customer Email',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'customer@company.com',
            'rows':1
        })
    )
    billing_address = forms.CharField(
        label='Billing Address',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '',
            'rows':1
        })
    )
    message = forms.CharField(
        label='Message/Note',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'message',
            'rows':1
        })
    )

class LineItemForm(forms.Form):
    
    service = forms.CharField(
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Service Name'
        })
    )
    description = forms.CharField(
        label='Description',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Enter Description',
            "rows":1
        })
    )
    quantity = forms.IntegerField(
        label='Qty',
        widget=forms.TextInput(attrs={
            'class': 'form-control input quantity',
            'placeholder': 'Quantity'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        label='Rate $',
        widget=forms.TextInput(attrs={
            'class': 'form-control input rate',
            'placeholder': 'Rate'
        })
    )
    # amount = forms.DecimalField(
    #     disabled = True,
    #     label='Amount $',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control input',
    #     })
    # )
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

invoice/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse
from django.views import View
from .models import LineItem, Invoice
from .forms import LineItemFormset, InvoiceForm

import pdfkit

class InvoiceListView(View):
    def get(self, *args, **kwargs):
        invoices = Invoice.objects.all()
        context = {
            "invoices":invoices,
        }

        return render(self.request, 'invoice/invoice-list.html', context)
    
    def post(self, request):        
        # import pdb;pdb.set_trace()
        invoice_ids = request.POST.getlist("invoice_id")
        invoice_ids = list(map(int, invoice_ids))

        update_status_for_invoices = int(request.POST['status'])
        invoices = Invoice.objects.filter(id__in=invoice_ids)
        # import pdb;pdb.set_trace()
        if update_status_for_invoices == 0:
            invoices.update(status=False)
        else:
            invoices.update(status=True)

        return redirect('invoice:invoice-list')

def createInvoice(request):
    """
    Invoice Generator page it will have Functionality to create new invoices, 
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LineItemFormset(request.GET or None)
        form = InvoiceForm(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset(request.POST)
        form = InvoiceForm(request.POST)
        
        if form.is_valid():
            invoice = Invoice.objects.create(customer=form.data["customer"],
                    customer_email=form.data["customer_email"],
                    billing_address = form.data["billing_address"],
                    date=form.data["date"],
                    due_date=form.data["due_date"], 
                    message=form.data["message"],
                    )
            # invoice.save()
            
        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0
            for form in formset:
                service = form.cleaned_data.get('service')
                description = form.cleaned_data.get('description')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')
                if service and description and quantity and rate:
                    amount = float(rate)*float(quantity)
                    total += amount
                    LineItem(customer=invoice,
                            service=service,
                            description=description,
                            quantity=quantity,
                            rate=rate,
                            amount=amount).save()
            invoice.total_amount = total
            invoice.save()
            try:
                generate_PDF(request, id=invoice.id)
            except Exception as e:
                print(f"********{e}********")
            return redirect('/')
    context = {
        "title" : "Invoice Generator",
        "formset": formset,
        "form": form,
    }
    return render(request, 'invoice/invoice-create.html', context)


def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "Meer Security Services",
            "address" :"Head office: Office no.1, 1st Floor, Building 3-C, 22nd commercial street, Phase 2, DHA, Karachi, Pakistan.",
            "phone": "0301 8208337",
            "email": "meer@securityservices.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        "due_date": invoice.due_date,
        "billing_address": invoice.billing_address,
        "message": invoice.message,
        "lineitem": lineitem,

    }
    return render(request, 'invoice/pdf_template.html', context)

def generate_PDF(request, id):
    # Use False instead of output path to save pdf to a variable
    pdf = pdfkit.from_url(request.build_absolute_uri(reverse('invoice:invoice-detail', args=[id])), False)
    response = HttpResponse(pdf,content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="invoice.pdf"'

    return response


def change_status(request):
    return redirect('invoice:invoice-list')

def view_404(request,  *args, **kwargs):

    return redirect('invoice:invoice-list')

invoice/templates/invoice/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     {% block custom_css %}{% endblock %}
    <title>Meer Security Services (MSS)</title>
</head>
<body>

    <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    <footer class="footer">
        <center><p class="has-text-weight-bold">All rights reserved to Meer Security Services Ltd.</p>
        </center>
        </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

invoice/templates/invoice/invoice-create.html
{% extends "invoice/base.html" %}{% load bulma_tags %}
{% block content %}
<br>
<section class="hero is-fullheight">
    <div class="container">
        <div class="card white-ter">
            <div class="hero-body">
                <form class="" method="POST" action="">{% csrf_token %}
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.customer|bulma}}
                        </div>

                        <div class="column is-one-third">
                            {{form.customer_email|bulma}}
                        </div>
                        <div class="column is-one-third">
                            {{form.message|bulma}}
                        </div>
                    </div>
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.billing_address|bulma}}
                        </div>
                        <div class="column is-one-third">
                            date: <input class="input" type="date" name="date">
                        </div>
                        <div class="column is-one-third">
                            due-date: <input class="input" type="date" name="due_date">
                        </div>
                    </div>


                    <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                        <tbody>
                            <thead>
                                <tr>
                                    <th>Product/Service</th>
                                    <th>Description</th>
                                    <th>QTY</th>
                                    <th>RATE</th>
                                    <th>AMOUNT(PKR)</th>
                                    <th>ADD</th>
                                </tr>
                                {{ formset.management_form }}
                                {% for form in formset %}
                                <tr>
                                    <td>{{form.service}}</td>
                                    <td>{{form.description}}</td>
                                    <td>{{form.quantity}}</td>
                                    <td>{{form.rate}}</td>
                                    <td class="amount"></td>
                                    <td>
                                        <div class="input-group-append">
                                            <button
                                                class="button is-small btn btn-success add-form-row">+</button>&nbsp;
                                            <!-- <button class="button is-small btn btn-warning remove-form-row">-</button> -->
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </thead>
                        </tbody>

                    </table>
                    <div class="row spacer">
                        <div class="col-4 offset-2">
                            <button type="submit" class="button btn btn-block is-info is-half">Create</button>
                        </div>
                    </div>
                    <br>
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-4">Total(PKR): <span id="total"></span></h3>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('table input').on("input", function () {
        var total = []
        var $tr = $(this).closest('tr');
        var textValue1 = $("input.rate", $tr).val();
        var textValue2 = $('input.quantity', $tr).val();
        amt = textValue1 * textValue2;
        // console.log(amt);
        $('.amount', $tr).html(amt);
        calc_total();
    });

    function calc_total() {
        var sum = 0;
        $(".amount").each(function () {
            sum += parseFloat($(this).text());
        });
        console.log(sum);
        $('#total').text(sum);
    }
</script>


<script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        console.log(newElement);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name')
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        // $("div.form-row.button.is-primary").not(":last").hide();
        // var conditionRow = $('.form-row:not(:last)');
        // conditionRow.find('.button.is-primary')
        // .hide();
        // .removeClass('btn-success').addClass('btn-danger')
        // .removeClass('add-form-row').addClass('remove-form-row')
        // .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('table tr:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

invoice/templates/invoice/invoice-list.html
{% extends 'invoice/base.html' %}
{% block content %}
<script>
    function filterInvoices() {
        var status = document.getElementById('filterStatus').value;
        var selectedMonth = document.getElementById('filterMonth').value;
        var selectedYear = document.getElementById('filterYear').value;
        var invoices = document.getElementsByClassName('invoice-row');

        for (var i = 0; i < invoices.length; i++) {
            var invoice = invoices[i];
            var isPaid = invoice.getAttribute('data-is-paid');
            var invoiceDate = new Date(invoice.getAttribute('data-invoice-date'));

            if (
                (status === 'all' || (status === '1' && isPaid === 'True') || (status === '0' && isPaid === 'False')) &&
                (selectedMonth === 'all' || invoiceDate.getMonth() == selectedMonth) &&
                (selectedYear === 'all' || invoiceDate.getFullYear() == selectedYear)
            ) {
                invoice.style.display = '';
            } else {
                invoice.style.display = 'none';
            }
        }
    }
</script>

<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>
</div>

<form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                All Orders / Change Order Status &nbsp;<button class="button is-rounded is-info">
                    <a href="{% url 'invoice:invoice-create' %}" class="has-text-white">Create Invoice</a></button>
            </p>
        </header>
        <div class="card-content">
            <div class="content">

                <div class="card has-background-white-ter">
                    <header class="card-header">
                        <p class="card-header-title">
                            Filter by Status
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="select is-rounded">
                            <select id="filterStatus" name="filterStatus" onchange="filterInvoices()">
                                <option value="all">All</option>
                                <option value="1">Paid</option>
                                <option value="0">Not Paid</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="card has-background-white-ter">
                    <header class="card-header">
                        <p class="card-header-title">
                            Filter by Month and Year
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="columns is-mobile">
                            <div class="column">
                                <div class="select is-rounded">
                                    <select id="filterMonth" name="filterMonth" onchange="filterInvoices()">
                                        <option value="all">All Months</option>
                                        <option value="0">January</option>
                                        <option value="1">February</option>
                                        <option value="2">March</option>
                                        <option value="3">April</option>
                                        <option value="4">May</option>
                                        <option value="5">June</option>
                                        <option value="6">July</option>
                                        <option value="7">August</option>
                                        <option value="8">September</option>
                                        <option value="9">October</option>
                                        <option value="10">November</option>
                                        <option value="11">December</option>
                                    </select>
                                </div>
                            </div>
                            <div class="column">
                                <input class="input" type="text" id="filterYear" name="filterYear" placeholder="Enter Year" oninput="filterInvoices()">
                            </div>
                        </div>
                    </div>
                </div>

                <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>INVOICE</th>
                            <th>CUSTOMER</th>
                            <th>DATE</th>
                            <th>DUE DATE</th>
                            <th>BALANCE</th>
                            <th>TOTAL</th>
                            <th>STATUS</th>
                            <th>View</th>
                            <th>DOWNLOAD</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for invoice in invoices %}
                        <tr class="invoice-row" data-is-paid="{{ invoice.get_status }}" data-invoice-date="{{ invoice.date }}">
                            <td>
                                <input class="checkbox" type="checkbox" value="{{invoice.id}}" name="invoice_id" size="1" />
                            </td>
                            <td width="1%">#{{invoice.id}}</td>
                            <td width="9%">{{invoice.customer}}</td>
                            <td>{{invoice.date}}</td>
                            <td>{{invoice.due_date}}</td>
                            <td width="1%"></td>
                            <td>{{invoice.total_amount}}</td>
                            <td class="level-right">
                                {% if invoice.get_status %}
                                    <a class="button is-small is-success" href="#">Paid</a>
                                {% else %}
                                    <a class="button is-small is-warning" href="#">Not Paid</a>
                                {% endif %}
                            </td>
                            <td width="1%">
                                <a href="{% url 'invoice:invoice-detail' id=invoice.id %}">
                                    <div class="button is-small is-info">View</div>
                                </a>
                            </td>
                            <td width="1%">
                                <a href="{% url 'invoice:invoice-download' id=invoice.id %}">Download</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />

    <div class="card has-background-white-ter">
        <header class="card-header">
            <p class="card-header-title">
                Change Order Status
            </p>
        </header>
        <div class="card-content">
            <div class="select is-rounded">
                <select id="status" name="status">
                    <option value="1">Paid</option>
                    <option value="0">Not Paid</option>
                </select>
            </div>
            <input class="button is-info is-rounded" type="submit" class="btn" value="Change Status" name="mybtn">
        </div>
    </div>
</form>

{% endblock content %}

invoice/templates/invoice/pdf_template (copy).html
<head>
<style>
    @page {
        size: a4 portrait;
        @frame header_frame {           /* Static Frame */
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 50pt; height: 40pt;
        }
        @frame content_frame {          /* Content Frame */
            left: 50pt; width: 512pt; top: 90pt; height: 632pt;
        }
        @frame footer_frame {           /* Another static Frame */
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
</style>
</head>

<body>
    <!-- Content for Static Frame 'header_frame' -->
    <div id="header_content">
    	<h3>Dennnis Ivanov Company</h3>
    </div>

    <!-- Content for Static Frame 'footer_frame' -->
    <div id="footer_content">(c) - page <pdf:pagenumber>
        of <pdf:pagecount>
    </div>

    <!-- HTML Content -->
    <table>
    		<tr>
    			<td>{{address}}</td>
    			<td>{{phone}}</td>
    		</tr>
    		<tr>
    			<td>{{city}} {{state}},</td>
    			<td>{{email}}</td>
    		</tr>
    		<tr>
    			<td>{{zipcode}}</td>
    			<td>{{website}}</td>
    		</tr>
    </table>

    <hr>

    <table>
    	<tr>
 
    		<th>Product</th>
    		<th>Price</th>
    		<th>Quantity</th>
    		<th>Total</th>
    	</tr>
    	<tr>
 
    		<td>Hosting Plan</td>
    		<td>$7.99</td>
    		<td>2</td>
    		<td>$15.98</td>
    	</tr>
    	<tr>
 
    		<td>consultation </td>
    		<td>$225</td>
    		<td>1</td>
    		<td>$225</td>
    	</tr>
    	<tr>
 
    		<td>Service Hours</td>
    		<td>$189</td>
    		<td>45.7</td>
    		<td>$8637.30</td>
    	</tr>
    </table>

    <hr>

    <p><strong>Total: $8878.28</strong></p>
</body>
</html>