invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, generate_PDF, view_PDF

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download'),
]

meer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from meerapp import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from invoice.views import (
    InvoiceListView,
    createInvoice,
    view_PDF,
    generate_PDF,
    change_status,
)
from meerapp.views import UniformFormView, UniformListView

urlpatterns = [
    # Authentication
    path('', views.index_view, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/create/', views.create_account, name='create_account'),
    path('accounts/', views.account_list, name='account_list'),
    path('accounts/<int:account_id>/', views.account_detail, name='account_detail'),
    #path('income-statement/', views.income_statement, name='income-statement'),
    #path('income_statement/', views.income_statement, name='income_statement'),
    path('balance_sheet/', views.balance_sheet, name='balance_sheet'),
    path('accounts/<int:account_id>/balance-sheet/', views.account_balance_sheet, name='account_balance_sheet'),
    path('invoices/<int:invoice_id>/', views.invoice_details, name='invoice_details'),
    path('invoices/<int:invoice_id>/create-item/', views.create_invoice_item, name='create_invoice_item'),
    path('add_journal_entry/', views.add_journal_entry, name='add_journal_entry'),
    path('accounts/trial_balance/', views.trial_balance, name='trial_balance'),
    path('journal-entries/<int:year>/<int:month>/', views.journal_entries_by_month_year, name='journal_entries_by_month_year'),
    path('add_employee/', views.add_employee, name='add_employee'),  # Add a new employee
    path('edit_employee/<int:employee_id>/', views.edit_employee, name='edit_employee'),  # Edit an employee
    path('delete_employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),  # Delete an employee
    path('employee_list/', views.employee_list, name='employee_list'),  # List all employees
    path('trash/', views.trash, name='trash'),
    path('restore_employee/<int:employee_id>/', views.restore_employee, name='restore_employee'),

    path('head_of_accounts/', views.head_of_accounts, name='head_of_accounts'),
    path('add_head_of_account/', views.add_head_of_account, name='add_head_of_account'),
    path('transactions/', views.transactions, name='transactions'),
    path('add_transaction/', views.add_transaction, name='add_transaction')
    ,
    path('mark-attendance/', views.mark_attendance, name='mark_attendance'),
    path('attendance-list/', views.attendance_list, name='attendance_list'),  # Add this line
    path('attendance-report/', views.attendance_report, name='attendance-report'),
    path('create_salary/', views.create_salary, name='create_salary'),
    path('list_salaries/', views.list_salaries, name='list_salaries'),
    path('calculate_salaries/', views.calculate_salaries, name='calculate_salaries'),
    path('weapons/', views.WeaponListView.as_view(), name='weapon-list'),
    path('weapons/<int:pk>/', views.WeaponDetailView.as_view(), name='weapon-detail'),
    path('weapons/add/', views.WeaponCreateView.as_view(), name='weapon-create'),
    path('location/<int:location_id>/', views.location_detail, name='location_detail'),
    path('location/<int:location_id>/assign_guards/', views.assign_guards, name='assign_guards'),
    path('location/add/', views.add_location, name='add_location'),
    path('locations/', views.location_list, name='location_list'),
    path('get_total_overtime/', views.get_total_overtime, name='get_total_overtime'),
    path('employee_report/<int:employee_id>/', views.employee_report, name='employee_report'),
    path('view_salary_detail/<int:salary_id>/', views.view_salary_detail, name='view_salary_detail'),
    path('uniform-form/', UniformFormView.as_view(), name='uniform_form'),
    path('uniform-list/', UniformListView.as_view(), name='uniform_list'),
    path('invoices/', include('invoice.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meerapp/urls.py
# accounting_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounting/', include('meer.urls')),
    path('', include("invoice.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meerapp/views.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Sum
from django.db import models
from .forms import TransactionForm, AccountForm, JournalEntryForm, HeadOfAccountForm
from .models import Account, Transaction, Attendance, Salary, HeadOfAccount, Uniform
from django.views.decorators.http import require_POST
from .forms import AttendanceForm, LocationForm
from django.contrib import messages
from .forms import SalaryForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Weapon, Location
from .forms import WeaponForm
from .forms import AssignGuardFormSet
from django.http import JsonResponse
def assign_guards(request, location_id):
    location = Location.objects.get(pk=location_id)

    initial_data = []
    assigned_guards = location.assigned_guards.all()

    for guard in assigned_guards:
        initial_data.append({'assigned_guard': guard})

    if request.method == "POST":
        formset = AssignGuardFormSet(request.POST, initial=initial_data)

        if formset.is_valid():
            location.assigned_guards.clear()
            for form in formset:
                assigned_guard = form.cleaned_data.get('assigned_guard')  # Use 'get' to avoid KeyError
                if assigned_guard:
                    location.assigned_guards.add(assigned_guard)
            return redirect('assign_guards', location_id=location_id)  # Redirect to the same page for further editing
    else:
        formset = AssignGuardFormSet(initial=initial_data)

    return render(request, 'assign_guards.html', {'formset': formset, 'location': location})

def location_list(request):
    locations = Location.objects.all()
    return render(request, 'location_list.html', {'locations': locations})

def add_location(request):
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('location_list')  # Redirect to a list of all locations.
    else:
        form = LocationForm()

    return render(request, 'add_location.html', {'form': form})


def location_detail(request, location_id):
    location = Location.objects.get(id=location_id)
    assigned_guards = Employee.objects.filter(duty_location=location)

    return render(request, 'location_detail.html', {'location': location, 'assigned_guards': assigned_guards})

class WeaponCreateView(CreateView):
    model = Weapon
    template_name = 'weapon_form.html'  # Create a corresponding HTML template for the form
    form_class = WeaponForm  # Use the custom form
    success_url = '/weapons/'  # Redirect to the weapon list after successful submission
class WeaponListView(ListView):
    model = Weapon
    template_name = 'weapon_list.html'  # Create a corresponding HTML template

class WeaponDetailView(DetailView):
    model = Weapon
    template_name = 'weapon_detail.html'  # Create a corresponding HTML template
#def create_salary(request):
 #   if request.method == 'POST':
  #      form = SalaryForm(request.POST)
   #     if form.is_valid():
    #        form.save()
     #       return redirect('list_salaries')
    #else:
     #   form = SalaryForm()

    # Fetch all employees
    #employees = Employee.objects.all()

    #return render(request, 'create_salary.html', {'form': form, 'employees': employees})

def list_salaries(request):
    salaries = Salary.objects.all()
    total_salary = sum(s.calculate_salary() for s in salaries)  # Calculate the total salary amount
    return render(request, 'list_salaries.html', {'salaries': salaries, 'total_salary': total_salary})

def calculate_salaries(request):
    salaries = Salary.objects.all()
    return render(request, 'calculate_salaries.html', {'salaries': salaries})

"""
import calendar

def attendance_report(request):
    if request.method == 'GET':
        month = request.GET.get('month')
        year = request.GET.get('year')

        if month and year:
            try:
                month = int(month)
                year = int(year)
            except ValueError:
                return render(request, 'attendance_report.html', {'error_message': 'Invalid month or year'})

            employees = Employee.objects.all()

            attendance_data = {}

            for employee in employees:
                # Calculate the number of days in the specified month and year
                _, total_days = calendar.monthrange(year, month)

                present_days = Attendance.objects.filter(
                    employee=employee, date__month=month, date__year=year, status='Present'
                ).count()

                absent_days = total_days - present_days

                if total_days > 0:
                    attendance_percentage = (present_days / total_days) * 100
                else:
                    attendance_percentage = 0

                attendance_data[employee] = {
                    'total_days': total_days,
                    'present_days': present_days,
                    'absent_days': absent_days,
                    'attendance_percentage': attendance_percentage,
                }

            return render(
                request,
                'attendance_report.html',
                {'attendance_data': attendance_data, 'month': month, 'year': year},
            )

    return render(request, 'attendance_report.html')
"""

from .models import Attendance, Employee
import calendar

def attendance_report(request):
    if request.method == 'GET':
        month = request.GET.get('month')
        year = request.GET.get('year')

        if month and year:
            try:
                month = int(month)
                year = int(year)
            except ValueError:
                return render(request, 'attendance_report.html', {'error_message': 'Invalid month or year'})

            employees = Employee.objects.all()

            attendance_data = {}

            for employee in employees:
                # Calculate the number of days in the specified month and year
                _, total_days = calendar.monthrange(year, month)

                present_days = Attendance.objects.filter(
                    employee=employee, date__month=month, date__year=year, status='Present'
                ).count()

                absent_days = total_days - present_days

                if total_days > 0:
                    attendance_percentage = (present_days / total_days) * 100
                else:
                    attendance_percentage = 0

                # Calculate the total overtime for the selected month and year
                total_overtime = Attendance.objects.filter(
                    employee=employee, date__month=month, date__year=year
                ).aggregate(Sum('overtime_count'))['overtime_count__sum'] or 0

                attendance_data[employee] = {
                    'total_days': total_days,
                    'present_days': present_days,
                    'absent_days': absent_days,
                    'attendance_percentage': attendance_percentage,
                    'total_overtime': total_overtime,  # Add total overtime to the data
                }

            return render(
                request,
                'attendance_report.html',
                {'attendance_data': attendance_data, 'month': month, 'year': year},
            )

    return render(request, 'attendance_report.html')

#def create_salary(request):
 #   employees = Employee.objects.all()

  #  if request.method == 'POST':
   #    if form.is_valid():
    #        form.save()
     #       return redirect('list_salaries')
    #else:
     #   form = SalaryForm()

    # Fetch total overtime for the selected employee, month, and year
    #employee_id = request.GET.get('employee', None)
    #month = request.GET.get('month', None)
    #year = request.GET.get('year', None)

    #total_overtime = 0  # Default value if not provided

    #if employee_id and month and year:
        # Perform the logic to fetch total overtime based on the provided parameters
        #total_overtime = calculate_total_overtime(employee_id, month, year)

    #return render(request, 'create_salary.html', {'form': form, 'employees': employees, 'total_overtime': total_overtime})

def create_salary(request):
    employees = Employee.objects.all()

    if request.method == 'POST':
        form = SalaryForm(request.POST)
        if form.is_valid():
            # Check if a salary entry already exists
            employee = form.cleaned_data['employee']
            month = form.cleaned_data['month']
            year = form.cleaned_data['year']

            existing_salary = Salary.objects.filter(employee=employee, month=month, year=year).exists()

            if existing_salary:
                return render(request, 'create_salary.html', {'form': form, 'employees': employees, 'total_overtime': 0, 'error_message': 'Salary already created for this employee in the selected month and year'})

            # Continue with the salary creation
            form.save()
            return redirect('list_salaries')
    else:
        form = SalaryForm()

    # Fetch total overtime for the selected employee, month, and year
    employee_id = request.GET.get('employee', None)
    month = request.GET.get('month', None)
    year = request.GET.get('year', None)

    total_overtime = 0  # Default value if not provided

    if employee_id and month and year:
        # Perform the logic to fetch total overtime based on the provided parameters
        total_overtime = calculate_total_overtime(employee_id, month, year)

    return render(request, 'create_salary.html', {'form': form, 'employees': employees, 'total_overtime': total_overtime})

def calculate_total_overtime(employee_id, month, year):
    try:
        employee = Employee.objects.get(id=employee_id)

meerapp/templates/account_list.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="box">
                    <h1 class="title is-3 has-text-centered">Account List</h1>

                    <ul>
                        {% for account in accounts %}
                            <li>
                                <strong>Account ID:</strong> {{ account.id }}<br>
                                <strong>Name:</strong> {{ account.name }}<br>
                                <strong>Account Type:</strong> {{ account.account_type }}<br>
                                <strong>Balance:</strong> {{ account.updated_balance }}
                                <a href="{% url 'account_detail' account.id %}" class="button is-link">View Details</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

meerapp/templates/add_uniform_issue.html
<!-- add_uniform_issue.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Uniform Issue</title>
</head>
<body>
    <h1>Add Uniform Issue</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Uniform Issue</button>
    </form>
</body>
</html>

meerapp/templates/add_uniform_item.html
<!-- add_uniform_item.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Uniform Item</title>
</head>
<body>
    <h1>Add Uniform Item</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Uniform Item</button>
    </form>
</body>
</html>

meerapp/templates/assign_guards.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title is-2 has-text-centered">Assign Guards to Location: {{ location.name }}</h1>

      <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ formset.non_form_errors }}

        <div id="formset-container" class="mb-4">
          {% for form in formset %}
            <div class="field is-grouped formset-form">
              {{ form.assigned_guard }}
              <button class="button is-danger delete-form" type="button">Delete</button>
            </div>
          {% endfor %}
        </div>

        <button class="button is-primary add-more-guards">Add more Guards</button>
        <input class="button is-success" type="submit" value="Assign Guards">
      </form>

      <!-- Display assigned guards -->
      <h2 class="title is-4 mt-5">Assigned Guards</h2>
      <ul class="content">
        {% for guard in location.assigned_guards.all %}
          <li>{{ guard.ename }} (MSS Number: {{ guard.MSS_number }})</li>
        {% endfor %}
      </ul>
    </div>
  </section>

  <script>
    // JavaScript to handle adding more guards dynamically
    $('.add-more-guards').on('click', function () {
      const formset = $('#id_form-TOTAL_FORMS').val();
      const lastForm = $('.formset-form:last');

      // Check if the last form has a selected guard
      if (lastForm.find('select').val()) {
        const newForm = lastForm.clone();
        newForm.find('select').val('');
        $('#formset-container').append(newForm);
        $('#id_form-TOTAL_FORMS').val(parseInt(formset) + 1);

        newForm.find('.delete-form').on('click', function () {
          newForm.remove();
          $('#id_form-TOTAL_FORMS').val(parseInt($('#id_form-TOTAL_FORMS').val()) - 1);
        });
      } else {
        alert("Please select a guard for the previous entry before adding more.");
      }
    });

    // JavaScript to handle deleting a form
    $(document).on('click', '.delete-form', function () {
      const form = $(this).parent();
      form.remove();
      $('#id_form-TOTAL_FORMS').val(parseInt($('#id_form-TOTAL_FORMS').val()) - 1);
    });
  </script>
{% endblock %}

meerapp/templates/attendance_list.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
    <div class="section">
        <div class="container">
            <h1 class="title">Marked Attendance Records</h1>

            <table class="table is-fullwidth">
                <thead>
                    <tr>
                        <th>Employee</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Location</th>
                        <th>Overtime Count</th>
                        <th>Overtime Location</th>
                    </tr>
                </thead>
                <tbody>
                    {% for record in marked_records %}
                        <tr>
                            <td>{{ record.employee }}</td>
                            <td>{{ record.date }}</td>
                            <td>{{ record.status }}</td>
                            <td>{{ record.location }}</td>
                            <td>{{ record.overtime_count }}</td>
                            <td>{{ record.overtime_location }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="buttons mt-4">
                <a href="{% url 'mark_attendance' %}" class="button is-link">Go Back to Mark Attendance</a>
                <a href="{% url 'attendance-report' %}" class="button is-primary">Generate Attendance Report</a>
            </div>
        </div>
    </div>
{% endblock %}

meerapp/templates/balance_sheet.html
<!DOCTYPE html>
<html>
<head>
    <title>Balance Sheet</title>
</head>
<body>
    <h1>Balance Sheet</h1>
    <h3>As of [Date]</h3>

    <h2>Assets:</h2>
    <p>Cash and Cash Equivalents: ${{ cash_and_equivalents }}</p>
    <p>Accounts Receivable: ${{ accounts_receivable }}</p>
    <p>Inventory: ${{ inventory }}</p>
    <p>Property, Plant, Equipment: ${{ property_equipment }}</p>
    <p>Less: Accumulated Depreciation: ${{ accumulated_depreciation }}</p>
    <p>Net Property, Plant, Equipment: ${{ net_property_equipment }}</p>
    <p>Investments: ${{ investments }}</p>
    <p>Other Assets: ${{ other_assets }}</p>
    <p>Total Current Assets: ${{ total_current_assets }}</p>

    <h2>Liabilities:</h2>
    <p>Accounts Payable: ${{ accounts_payable }}</p>
    <p>Short-Term Loans: ${{ short_term_loans }}</p>
    <p>Accrued Expenses: ${{ accrued_expenses }}</p>
    <p>Long-Term Debt: ${{ long_term_debt }}</p>
    <p>Other Liabilities: ${{ other_liabilities }}</p>
    <p>Total Current Liabilities: ${{ total_current_liabilities }}</p>

    <h2>Equity:</h2>
    <p>Common Stock: ${{ common_stock }}</p>
    <p>Retained Earnings: ${{ retained_earnings }}</p>
    <p>Total Equity: ${{ total_equity }}</p>

    <h2>Total Liabilities and Equity:</h2>
    <p>Total Liabilities and Equity: ${{ total_liabilities_equity }}</p>
</body>
</html>

meerapp/templates/create_invoice_item.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Invoice Item</title>
</head>
<body>
    <h1>Create Invoice Item for Invoice {{ invoice.invoice_number }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Item</button>
    </form>
    <a href="{% url 'invoice_details' invoice.id %}">Back to Invoice Details</a>
</body>
</html>

meerapp/templates/income_statement.html
<!DOCTYPE html>
<html>
<head>
    <title>Income Statement</title>
</head>
<body>
    <h1>Income Statement</h1>
    <p>Income: ${{ income }}</p>
    <p>Expenses: ${{ expenses }}</p>
    <p>Net Income: ${{ net_income }}</p>
</body>
</html>

meerapp/templates/item_list.html
<!-- in templates/item_list.html -->
<h1>Item List</h1>
<ul>
    {% for item in items %}
        <li>{{ item.name }}</li>
    {% endfor %}
</ul>

meerapp/templates/logout.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
  <section class="section">
    <div class="container has-text-centered">
      <h2 class="title is-2">Logout</h2>

      <p class="subtitle is-4">You have been logged out.</p>
      <a class="button is-info" href="{% url 'index' %}">Login</a>


    </div>
  </section>
{% endblock %}

meerapp/templates/profile.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="box">
          <h1 class="title is-3 has-text-centered">Welcome, {{ request.user.username }}!</h1>

          <div class="menu">
            <p class="menu-label">Transaction</p>
            <ul class="menu-list">
              <li><a href="{% url 'add_head_of_account' %}">Add Head of Account</a></li>
              <li><a href="{% url 'transactions' %}">Transactions</a></li>
              <li><a href="{% url 'add_transaction' %}">Add Transaction</a></li>
            </ul>

            <p class="menu-label">Account</p>
            <ul class="menu-list">
              <li><a href="{% url 'create_account' %}">Create Account</a></li>
              <li><a href="{% url 'account_list' %}">Account List</a></li>
            </ul>

            <p class="menu-label">Invoice</p>
            <ul class="menu-list">
              <li><a href="{% url 'invoice:invoice-create' %}">Go to Invoice Creation</a></li>
              <li><a href="{% url 'invoice:invoice-list' %}">Go to Invoice List</a></li>
            </ul>

            <p class="menu-label">Employee</p>
            <ul class="menu-list">
              <li><a href="{% url 'add_employee' %}">Add Employee</a></li>
              <li><a href="{% url 'uniform_form' %}">Add Uniform</a></li>
              <li><a href="{% url 'employee_list' %}">Active Employee</a></li>
              <li><a href="{% url 'trash' %}">In Active Employee</a></li>
            </ul>

            <p class="menu-label">Attendance</p>
            <ul class="menu-list">
              <li><a href="{% url 'mark_attendance' %}">Mark Attendance</a></li>
              <li><a href="{% url 'attendance-report' %}">Attendance Report</a></li>
            </ul>

            <p class="menu-label">Create Salary</p>
            <ul class="menu-list">
              <li><a href="{% url 'create_salary' %}">Create Salary</a></li>
              <li><a href="{% url 'list_salaries' %}">All Salaries</a></li>
            </ul>

            <p class="menu-label">Weapons</p>
            <ul class="menu-list">
              <li><a href="{% url 'weapon-create' %}">Add Weapon</a></li>
              <li><a href="{% url 'weapon-list' %}">Weapon List</a></li>
              <li><a href="{% url 'location_list' %}">Go to Locations</a></li>
            </ul>
          </div>

          <p class="has-text-centered"><a href="{% url 'logout' %}" class="button is-danger">Logout</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

meerapp/templates/trial_balance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trial Balance</title>
</head>
<body>
    <h1>Trial Balance</h1>
    <table>
        <tr>
            <th>Account</th>
            <th>Balance</th>
        </tr>
        {% for account, balance in trial_balance.items %}
            <tr>
                <td>{{ account }}</td>
                <td>{{ balance }}</td>
            </tr>
        {% endfor %}
    </table>

    <h2>Journal Entries</h2>
    <table>
        <tr>
            <th>Date</th>
            <th>Account</th>
            <th>Purpose of transaction</th>
            <th>Debit Amount</th>
            <th>Credit Amount</th>
        </tr>
        {% for entry in journal_entries %}
            <tr>
                <td>{{ entry.date }}</td>
                <td>{{ entry.account.name }}</td>
                <td>{{ entry.entry_name }}</td>
                <td>{{ entry.debit_amount }}</td>
                <td>{{ entry.credit_amount }}</td>
            </tr>
        {% endfor %}
    </table>

    <br>
    <a href="{% url 'add_journal_entry' %}">Add Journal Entry</a>
</body>
</html>

meerapp/templates/uniform_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Uniform List</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 20px;
      box-sizing: border-box;
    }

    h2 {
      color: #333;
    }

    ul {
      list-style-type: none;
      padding: 0;
    }

    li {
      margin-bottom: 10px;
    }

    p {
      color: #888;
    }
  </style>
</head>
<body>

<h2>Uniform List</h2>

{% if uniforms %}
  <ul>
    {% for uniform in uniforms %}
      <li>
        <strong>{{ uniform.employee }}</strong> - {{ uniform.date|date:"F d, Y" }} - {{ uniform.status }}
      </li>
    {% endfor %}
  </ul>

<h3>All Line Items</h3>
<ul>
  {% for lineitem in all_line_items %}
    <li>
      {{ lineitem.uniform_product }} - {{ lineitem.description }} - Quantity: {{ lineitem.quantity }}
    </li>
  {% endfor %}
</ul>


{% else %}
  <p>No uniforms available.</p>
{% endif %}

</body>
</html>

meerapp/templates/weapon_form.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}

{% block content %}
<div class="columns is-centered">
  <div class="column is-half">
    <section class="section">
      <center><h1 class="title">Add Weapon</h1></center>
      <form method="post" class="box">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="field is-grouped">
          <div class="control">
            <button type="submit" class="button is-primary">Add Weapon</button>
          </div>
        </div>
      </form>
      <p><a href="{% url 'weapon-list' %}" class="button is-link">Back to Weapon List</a></p>
    </section>
  </div>
</div>
{% endblock %}